---
- name: Install zsh
  package:
    name: zsh
    state: present
  when: ansible_os_family != 'Darwin'

- name: Install antigen
  package:
    name: antigen
    state: present

- name: Copy zshrc
  copy:
    src: zshrc.zsh
    dest: ~/.zshrc

- name: Create ~/.zshrc.d directory
  file:
    path: ~/.zshrc.d
    state: directory

