---
- name: Install packages
  package:
    name:
      - vim
      - git
    state: present

- name: Copy vimrc
  copy:
    src: vimrc
    dest: ~/.vimrc

- include_tasks: "{{ ansible_os_family | lower }}.yml"
